In [144]:
# Smart Marketing Prediction System (ML Pipeline Project)
# Scenario
# A fast-growing e-commerce company called ShopEasy is struggling with inefficient marketing campaigns.

# Every day thousands of users visit their website. The marketing team spends a large amount of money showing ads, discounts, and promotional emails, but they don't know which customers are actually likely to buy something.

# Currently:

# Many customers browse but never purchase

# Marketing money is wasted on the wrong users

# The company wants to predict purchase probability

# The data science team has been asked to build a machine learning system that predicts whether a customer will purchase a product during a session.

# If the system predicts high probability of purchase, the system will:

# show personalized product recommendations

# offer targeted discounts

# prioritize marketing campaigns

# If the system predicts low probability, the company will avoid spending marketing resources.

# However, the dataset contains both numerical and categorical features, so the data science team must design a complete ML pipeline.

In [145]:
import pandas as pd

In [146]:
df=pd.read_excel("DatasetCapstoneProject3.xlsx")

In [147]:
df.isnull().sum()

CustomerID            0
Age                   0
Gender                0
Device                0
Traffic_Source        0
Time_on_Website       0
Pages_Visited         0
Ad_Clicks             0
Previous_Purchases    0
Purchased             0
dtype: int64

In [148]:
df.head()

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0

In [149]:
from sklearn.preprocessing import StandardScaler ,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [150]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Device', 'Traffic_Source',
       'Time_on_Website', 'Pages_Visited', 'Ad_Clicks', 'Previous_Purchases',
       'Purchased'],
      dtype='object')

In [151]:
dc=df.copy()

In [152]:
X=dc.drop(["Purchased","CustomerID"],axis=1)
y=dc["Purchased"]
X.head(2)

,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases
0,23,Male,Mobile,Social Media,5,3,1,0
1,35,Female,Desktop,Search Engine,12,8,3,2

In [153]:
numerical_feature=["Age","Time_on_Website","Pages_Visited","Ad_Clicks","Previous_Purchases"]
categorical_feature=["Gender","Device","Traffic_Source"]

In [ ]:
#It is working as manager to assign model to each category
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_feature),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_feature)
    ]
)

In [ ]:
#Combining two pipeline
pipeline = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

In [156]:
# Hyperparameter Tuning using GridSearchCV
from sklearn.model_selection import GridSearchCV


param_grid = {
    "model__C": [0.01,0.1,1,10],
    "model__solver": ["lbfgs"]
}

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=3,
    scoring="accuracy"
)

In [157]:
# Train-Test Split
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [158]:
# Train Model with Hyperparameter Tuning
grid_search.fit(X_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['Age',
                                                                          'Time_on_Website',
                                                                          'Pages_Visited',
                                                                          'Ad_Clicks',
                                                                          'Previous_Purchases']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Gender',
                                                                          'Device',
                                                                          'Traffic_Source'])])),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             param_grid={'model__C': [0.01, 0.1, 1, 10],
                         'model__solver': ['lbfgs']},
             scoring='accuracy')

In [159]:
from sklearn.metrics import classification_report


print("Best Parameters:", grid_search.best_params_)
y_pred = grid_search.predict(X_test)
print(classification_report(y_test, y_pred))

Best Parameters: {'model__C': 1, 'model__solver': 'lbfgs'}
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

In [ ]:
#Testing Data What it going to predict
test_data = pd.DataFrame({
    "CustomerID":[101,102,103,104,105],
    "Age":[28,45,33,24,39],
    "Gender":["Male","Female","Female","Male","Male"],
    "Device":["Mobile","Desktop","Tablet","Mobile","Desktop"],
    "Traffic_Source":["Organic","Ads","Social","Organic","Ads"],
    "Time_on_Website":[5.2,12.5,7.8,3.1,10.4],
    "Pages_Visited":[4,9,6,2,8],
    "Ad_Clicks":[1,3,2,0,4],
    "Previous_Purchases":[1,4,2,0,3]
})

predictions = grid_search.predict(test_data)

test_data["Predicted_Purchase"] = predictions
df.head(5)

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0

In [ ]:
#We are checking accuracy Score 
from sklearn.metrics import accuracy_score


testing_data = pd.read_csv('testing.csv')
Xt = testing_data.drop(columns=['CustomerID', 'Purchased'])
yt = testing_data['Purchased']
test_pred = grid_search.predict(Xt)
print(f'Accuracy Score: {accuracy_score(test_pred, yt).__round__(4)*100}%')

Accuracy Score: 88.89%

In [162]:
df.head(5)

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0